#!/bin/sh

. "${XDG_CONFIG_HOME:-$HOME/.config}/osuget/config"

get_download_url() {
	echo "https://osu.ppy.sh/beatmapsets/$1/download"
}

get_page_url() {
	echo "https://osu.ppy.sh/beatmapsets/$1"
}

get_beatmapset_id() {
	ID=$(echo "$@" | sed -E 's!.*(osuget:|https:\/\/osu\.ppy\.sh\/(b|beatmapsets)\/)([0-9]+).*!\3!')
	if echo "$@" | grep "https://osu.ppy.sh/b/" > /dev/null; then
		BEATMAPSET_URL=$(curl -L --head "$@" | grep location | sed "s/location: //")
		get_beatmapset_id "$BEATMAPSET_URL"
	else
		echo "$ID"
	fi
}

download() {
	DOWNLOAD_PATH=$(echo "$1" | sed "s!^~/!$HOME/!")
	DOWNLOAD_URL="$2"
	REFERER_URL="$3"
	# notify-send Debug "$DOWNLOAD_URL $DOWNLOAD_PATH $REFERER_URL"
	wget --timestamping --content-disposition --header="$OSU_COOKIE" --header "Referer: $REFERER_URL" "$DOWNLOAD_URL" --directory-prefix="$DOWNLOAD_PATH"
}

notify() {
	notify-send --app-name=osuget --urgency=low "$1" "$2"
}

INPUT="$1"
GAMEDIR="${OSU_GAMEDIR:-$2}"
ID=$(get_beatmapset_id "$INPUT")

if [ ! "$ID" ]; then
	echo osuget: invalid input, enter beatmapset id or url
	exit 1
fi

notify "BeatmapSet download started..." "ID: $ID"

download "$GAMEDIR" "$(get_download_url "$ID")" "$(get_page_url "$ID")"

notify "BeatmapSet download finished!" "ID: $ID"
